# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d10fc2066c23a5ff78bb42fb8bd238438bf623dd54d87437a791dfce08532b154efeb0ade2ccecfd31aef7219a0cca418f2aeb4c80b5bf1378bc2e06c6dc2a8f

test:
  secret_key_base: b6ad71f4c80e5b3dd627f7a726de4fcea9ed03e5e2db604b7e3207f80fdd20f2e9dfe18cb6cc42e6066cbf57b92438a3deb72d4f62536601e884226b6cc589cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
